/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * AddboothType.java
 *
 * Created on Nov 12, 2010, 4:50:44 PM
 */

package boothType;

import dataLayer.DBHelper;
import expomanagement.Main;
import java.awt.Frame;
import java.sql.CallableStatement;
import javax.swing.JOptionPane;
import javax.swing.UIManager;

/**
 *
 * @author namh3o
 */
public class AddboothType extends javax.swing.JFrame {

    OperationBoothType ob  = new OperationBoothType();
    
    /** Creates new form AddboothType */
    public AddboothType() {
        try {
            UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
        }
        catch (Exception ex) {
            ex.printStackTrace();
        }
        initComponents();
        ob.buildCbExpo(cbExpo);
    }
    private boolean checkformBoothType(){
        if(cbExpo.getSelectedIndex() == 0){
            JOptionPane.showMessageDialog(this,"Please,select Expo");
            cbExpo.requestFocus();
            return false;
        }
        if(txtBTName.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please,Enter Name of BoothType");
            txtBTName.requestFocus();
            return false;
        }
        if(txtBTHeight.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please,Enter BoothType Height");
            txtBTHeight.requestFocus();
            return false;
        }
        try {
            Long.parseLong(txtBTHeight.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "BoothType Height must Number");
            return false;
        }
        if(txtBTWidth.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please,Enter BoothType Width");
            txtBTWidth.requestFocus();
            return false;
        }
        try {
            Long.parseLong(txtBTWidth.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "BoothType Width must Number");
            return false;
        }
        if(txtBremain.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please,Enter Booth Remain");
            txtBremain.requestFocus();
            return false;
        }
        try {
            Long.parseLong(txtBremain.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Booth Remain must Number");
            return false;
        }
        if(txtBlength.getText().equals("")){
            JOptionPane.showMessageDialog(this,"Please,Enter Booth Length");
            txtBlength.requestFocus();
            return false;
        }
        try {
            Long.parseLong(txtBlength.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Booth Length must Number");
            return false;
        }
        
        return true;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        cbExpo = new javax.swing.JComboBox();
        jLabel4 = new javax.swing.JLabel();
        txtBTName = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        txtBTHeight = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        txtBTWidth = new javax.swing.JTextField();
        txtBremain = new javax.swing.JTextField();
        txtBlength = new javax.swing.JTextField();
        btnAdd = new javax.swing.JButton();
        btnReset = new javax.swing.JButton();
        btnClose = new javax.swing.JButton();

        org.jdesktop.layout.GroupLayout jPanel1Layout = new org.jdesktop.layout.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Add New Booth Type");

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Add BoothType"));

        jLabel2.setText("Expo :");

        cbExpo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel4.setText("BoothType Name :");

        jLabel5.setText("BoothType Height :");

        jLabel6.setText("BoothType Width :");

        jLabel8.setText("Booth Remain :");

        jLabel9.setText("Booth Length :");

        org.jdesktop.layout.GroupLayout jPanel3Layout = new org.jdesktop.layout.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(jLabel6)
                    .add(jLabel8)
                    .add(jLabel9)
                    .add(jLabel5)
                    .add(jLabel4)
                    .add(jLabel2))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(org.jdesktop.layout.GroupLayout.TRAILING, txtBTName, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .add(txtBTHeight, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .add(txtBlength, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .add(txtBremain, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .add(txtBTWidth, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, 153, Short.MAX_VALUE)
                    .add(cbExpo, 0, 153, Short.MAX_VALUE))
                .add(37, 37, 37))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel2)
                    .add(cbExpo, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel4)
                    .add(txtBTName, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel5)
                    .add(txtBTHeight, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, 19, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(org.jdesktop.layout.LayoutStyle.UNRELATED)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel6)
                    .add(txtBTWidth, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel8)
                    .add(txtBremain, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .add(18, 18, 18)
                .add(jPanel3Layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(jLabel9)
                    .add(txtBlength, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(50, Short.MAX_VALUE))
        );

        btnAdd.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expomanagement/icon_func/13.png"))); // NOI18N
        btnAdd.setText("Add");
        btnAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAddActionPerformed(evt);
            }
        });

        btnReset.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expomanagement/icon_func/76.png"))); // NOI18N
        btnReset.setText("Reset");
        btnReset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResetActionPerformed(evt);
            }
        });

        btnClose.setIcon(new javax.swing.ImageIcon(getClass().getResource("/expomanagement/icon_func/33.png"))); // NOI18N
        btnClose.setText("Close");
        btnClose.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCloseActionPerformed(evt);
            }
        });

        org.jdesktop.layout.GroupLayout layout = new org.jdesktop.layout.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
                    .add(layout.createSequentialGroup()
                        .addContainerGap()
                        .add(jPanel3, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .add(layout.createSequentialGroup()
                        .add(34, 34, 34)
                        .add(btnAdd)
                        .add(34, 34, 34)
                        .add(btnReset)
                        .add(28, 28, 28)
                        .add(btnClose)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(org.jdesktop.layout.GroupLayout.LEADING)
            .add(layout.createSequentialGroup()
                .addContainerGap()
                .add(jPanel3, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE, org.jdesktop.layout.GroupLayout.DEFAULT_SIZE, org.jdesktop.layout.GroupLayout.PREFERRED_SIZE)
                .add(18, 18, 18)
                .add(layout.createParallelGroup(org.jdesktop.layout.GroupLayout.BASELINE)
                    .add(btnAdd)
                    .add(btnClose)
                    .add(btnReset))
                .addContainerGap(21, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCloseActionPerformed
        // TODO add your handling code here:
        dispose();
    }//GEN-LAST:event_btnCloseActionPerformed

    private void btnResetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResetActionPerformed
        // TODO add your handling code here:
        cbExpo.setSelectedIndex(0);
        txtBTName.setText("");
        txtBTHeight.setText("");
        txtBTWidth.setText("");
        txtBlength.setText("");
        txtBremain.setText("");
    }//GEN-LAST:event_btnResetActionPerformed

    private void btnAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAddActionPerformed
        // TODO add your handling code here:
        if(checkformBoothType()){
            try {
            DBHelper db = null;
            db = new DBHelper();
            db.openConnection();

            String name = txtBTName.getText().trim();
            int EID = ob.returnIdExpo(cbExpo);
            float height = Float.parseFloat(txtBTHeight.getText().trim());
            float width = Float.parseFloat(txtBTWidth.getText().trim());
            int remain = Integer.parseInt(txtBremain.getText().trim());
            int length = Integer.parseInt(txtBlength.getText().trim());

            //tao giao dien de thuc thi store
            CallableStatement cs = db.getConnection().prepareCall("{call AddBoothType(?,?,?,?,?,?)}");
            //truyen tham so cho store

            cs.setString(1, name);
            cs.setInt(2, EID);
            cs.setFloat(3, height);
            cs.setFloat(4, width);
            cs.setInt(5, remain);
            cs.setInt(6, length);

            //thuc thi store
            cs.execute();
            JOptionPane.showMessageDialog(null, "One new Booth Type has been added","Add new Booth Type",JOptionPane.INFORMATION_MESSAGE);
            dispose();

            //lay gia tri tham so ra
            } catch (Exception ex) {
                JOptionPane.showMessageDialog(null, "An error occurred during execution","Add new Booth Type",JOptionPane.ERROR_MESSAGE);
                ex.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnAddActionPerformed

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddboothType().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdd;
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnReset;
    private javax.swing.JComboBox cbExpo;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JTextField txtBTHeight;
    private javax.swing.JTextField txtBTName;
    private javax.swing.JTextField txtBTWidth;
    private javax.swing.JTextField txtBlength;
    private javax.swing.JTextField txtBremain;
    // End of variables declaration//GEN-END:variables

}
